import network as nx
import maplotlib.pyplot as plt

#Cria grafo vazio
G = nx.Graph()

#Adiciona Vértices
G.add_node('Chaos')
G.add_node('Erebus')
G.add_node('Nyx')
G.add_node('Charon')
G.add_node('Tartarus')
G.add_node('Gaia')
G.add_node('Ourea')
G.add_node('Typhone')
G.add_node('Echidna')
G.add_node('Orthrus')
G.add_node('Cerberus')
G.add_node('Colchian Dragon')
G.add_node('Chimera')
G.add_node('Hydra')
G.add_node('Sphinx')
G.add_node('Uranus')
G.add_node('Oceanus')
G.add_node('Tethys')
G.add_node('Hyperion')
G.add_node('Theia')
G.add_node('Crius')
G.add_node('Cronus')
G.add_node('Rhea')
G.add_node('Themis')
G.add_node('Iapetus')
G.add_node('Mnemosyne')
G.add_node('Coeus')
G.add_node('Phoebe')
G.add_node('Pontus')
G.add_node('Aether')
G.add_node('Hemera')
G.add_node('Thalassa')
G.add_node('Thaumus')
G.add_node('Iris')
G.add_node('Harpies')
G.add_node('Porcys')
G.add_node('Ceto')
G.add_node('Sirens')
G.add_node('Scylla')
G.add_node('Gorgons')
G.add_node('Graeae')
G.add_node('Eurybia')
G.add_node('Asia')
G.add_node('Nereus')
G.add_node('Doris')
G.add_node('Tyche')
G.add_node('Perse')
G.add_node('Euronyme')
G.add_node('Metis')
G.add_node('Styx')
G.add_node('Pleone')
G.add_node('Helios')
G.add_node('Selene')
G.add_node('Eos')
G.add_node('Astraeus')
G.add_node('Pallas')
G.add_node('Atlas')
G.add_node('Prometheus')
G.add_node('Epimetheus')
G.add_node('Pandora')
G.add_node('Amphitrite')
G.add_node('Poseidon')
G.add_node('Triton')
G.add_node('Demeter')
G.add_node('Zeus')
G.add_node('Hera')
G.add_node('Hades')
G.add_node('Hestia')
G.add_node('Maia')
G.add_node('Leto')
G.add_node('Asteria')
G.add_node('Athena')
G.add_node('Hebe')
G.add_node('Hephaestus')
G.add_node('Ares')
G.add_node('Aphrodite')
G.add_node('Adonis')
G.add_node('Hermes')
G.add_node('Apollo')
G.add_node('Artemis')

#Adiciona Arestas
G.add_edge('Chaos', 'Erebus')
