import network as nx
import maplotlib.pyplot as plt

#Cria grafo vazio
G = nx.Graph()

#Adiciona Vértices
G.add_node('Chaos')
G.add_node('Erebus')
G.add_node('Nyx')
G.add_node('Charon')
G.add_node('Tartarus')
G.add_node('Gaia')
G.add_node('Ourea')
G.add_node('Typhone')
G.add_node('Echidna')
G.add_node('Orthrus')
G.add_node('Cerberus')
G.add_node('Colchian Dragon')
G.add_node('Chimera')
G.add_node('Hydra')
G.add_node('Sphinx')
G.add_node('Uranus')
G.add_node('Oceanus')
G.add_node('Tethys')
G.add_node('Hyperion')
G.add_node('Theia')
G.add_node('Crius')
G.add_node('Cronus')
G.add_node('Rhea')
G.add_node('Themis')
G.add_node('Iapetus')
G.add_node('Mnemosyne')
G.add_node('Coeus')
G.add_node('Phoebe')
G.add_node('Pontus')
G.add_node('Aether')
G.add_node('Hemera')
G.add_node('Thalassa')
G.add_node('Thaumus')
G.add_node('Iris')
G.add_node('Harpies')
G.add_node('Porcys')
G.add_node('Ceto')
G.add_node('Sirens')
G.add_node('Scylla')
G.add_node('Gorgons')
G.add_node('Graeae')
G.add_node('Eurybia')
G.add_node('Asia')
G.add_node('Nereus')
G.add_node('Doris')
G.add_node('Tyche')
G.add_node('Perse')
G.add_node('Euronyme')
G.add_node('Metis')
G.add_node('Styx')
G.add_node('Pleone')
G.add_node('Helios')
G.add_node('Selene')
G.add_node('Eos')
G.add_node('Astraeus')
G.add_node('Pallas')
G.add_node('Atlas')
G.add_node('Prometheus')
G.add_node('Epimetheus')
G.add_node('Pandora')
G.add_node('Amphitrite')
G.add_node('Poseidon')
G.add_node('Triton')
G.add_node('Demeter')
G.add_node('Zeus')
G.add_node('Hera')
G.add_node('Hades')
G.add_node('Hestia')
G.add_node('Maia')
G.add_node('Leto')
G.add_node('Asteria')
G.add_node('Athena')
G.add_node('Hebe')
G.add_node('Hephaestus')
G.add_node('Ares')
G.add_node('Aphrodite')
G.add_node('Adonis')
G.add_node('Hermes')
G.add_node('Apollo')
G.add_node('Artemis')

#Adiciona Arestas
G.add_edge('Chaos', 'Erebus')
G.add_edge('Gorgons', 'Graeae')
G.add_edge('Eurybia', 'Astraeus')
G.add_edge('Eurybia', 'Pallas')
G.add_edge('Asia', 'Doris')
G.add_edge('Asia', 'Tyche')
G.add_edge('Asia', 'Perse')
G.add_edge('Asia', 'Eurynome')
G.add_edge('Asia', 'Metis')
G.add_edge('Asia', 'Styx')
G.add_edge('Asia', 'Pleone')
G.add_edge('Nereus', 'Doris')
G.add_edge('Nereus', 'Amphitrite')
G.add_edge('Nereus', 'Thetis')
G.add_edge('Doris', 'Tyche')
G.add_edge('Doris', 'Perse')
G.add_edge('Doris', 'Eurynome')
G.add_edge('Doris', 'Metis')
G.add_edge('Doris', 'Styx')
G.add_edge('Doris', 'Pleone')
G.add_edge('Doris', 'Amphitrite')
G.add_edge('Doris', 'Thetis')
G.add_edge('Tyche', 'Perse')
G.add_edge('Tyche', 'Eurynome')
G.add_edge('Tyche', 'Metis')
G.add_edge('Tyche', 'Styx')
G.add_edge('Tyche', 'Pleone')
G.add_edge('Perse', 'Eurynome')
G.add_edge('Perse', 'Metis')
G.add_edge('Perse', 'Styx')
G.add_edge('Perse', 'Pleone')
G.add_edge('Perse', 'Helios')
G.add_edge('Euronyme', 'Metis')
G.add_edge('Euronyme', 'Styx')
G.add_edge('Euronyme', 'Pleone')
G.add_edge('Euronyme', 'Zeus')
G.add_edge('Metis', 'Styx')
G.add_edge('Metis', 'Pleone')
G.add_edge('Metis', 'Zeus')
G.add_edge('Metis', 'Atena')
G.add_edge('Styx', 'Pleone')
G.add_edge('Styx', 'Pallas')
G.add_edge('Pleone', 'Atlas')
G.add_edge('Pleone', 'Maia')
G.add_edge('Helios', 'Selene')
G.add_edge('Helios', 'Eos')
G.add_edge('Selene', 'Eos')
G.add_edge('Eos', 'Astraeus')
G.add_edge('Astraeus', 'Pallas')
G.add_edge('Atlas', 'Prometheus')
G.add_edge('Atlas', 'Epimetheus')
G.add_edge('Atlas', 'Maia')
G.add_edge('Prometheus', 'Epimetheus')
G.add_edge('Epimetheus', 'Pandora')
G.add_edge('Amphitrite', 'Poseidon')
G.add_edge('Amphitrite', 'Triton')
G.add_edge('Poseidon', 'Triton')
G.add_edge('Poseidon', 'Demeter')
G.add_edge('Poseidon', 'Zeus')
G.add_edge('Poseidon', 'Hera')
G.add_edge('Poseidon', 'Hades')
G.add_edge('Poseidon', 'Hestia')
G.add_edge('Demeter', 'Zeus')
G.add_edge('Demeter', 'Hera')
G.add_edge('Demeter', 'Hades')
G.add_edge('Demeter', 'Hestia')
G.add_edge('Zeus', 'Hera')
G.add_edge('Zeus', 'Hades')
G.add_edge('Zeus', 'Hestia')
G.add_edge('Zeus', 'Hephaestus')
G.add_edge('Zeus', 'Ares')
G.add_edge('Zeus', 'Apollo')
G.add_edge('Zeus', 'Artemis')
G.add_edge('Zeus', 'Maia')
G.add_edge('Zeus', 'Hebe')
G.add_edge('Zeus', 'Leto')
G.add_edge('Hera', 'Hebe')
G.add_edge('Hera', 'Hephaestus')
G.add_edge('Hera', 'Ares')
G.add_edge('Hera', 'Hades')
G.add_edge('Hera', 'Hestia')
G.add_edge('Hades', 'Hestia')
G.add_edge('Maia', 'Hermes')
G.add_edge('Leto', 'Apollo')
G.add_edge('Leto', 'Artemis')
G.add_edge('Leto', 'Asteria')
G.add_edge('Hebe', 'Hephaestus')
G.add_edge('Hebe', 'Ares')
G.add_edge('Hephaestus', 'Ares')
G.add_edge('Aphrodite', 'Adonis')
G.add_edge('Apollo', 'Artemis')